name: Documentation
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: macOS-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          bundle update --bundler
          bundle install
      - name: Publish Docs
        env:
          GITHUB_API_TOKEN: ${{ secrets.GH_UIAS_TOKEN }}
        run: ./.scripts/update-gh-pages
